spring.application.name=codolog

# MongoDB connection
spring.data.mongodb.uri=mongodb+srv://juniordeveloperinfous_db_user:7KK05DX2US0RJutG@codolog.mncsvos.mongodb.net/codolog?retryWrites=true&w=majority
spring.data.mongodb.database=codolog

# Spring Security default user
spring.security.user.name=admins
spring.security.user.password=1234

# Mail settings
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=shivamdubeyaptop@gmail.com
spring.mail.password=wcsn wwzx fpzz gbya
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Custom file storage path
file.upload-dir=uploads/profile-photos/
